name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Build app
        run: xcodebuild -project "Cal AI/Cal AI.xcodeproj" \
                        -scheme "Cal AI" \
                        -sdk iphonesimulator \
                        -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' \
                        clean build
